#!/usr/bin/env python
from os import chdir as cd, listdir as ls, getcwd as pwd
from subprocess import run, getoutput
from sys import argv
from configparser import ConfigParser

config = ConfigParser()
config.read('/home/roshan/repos/web_of_notes/config.ini')

latex_dir = config['config']['latex_dir']
pdf_dir = config['config']['pdf_dir']
raw_dir = config['config']['raw_dir']
tags_dir = config['config']['tags_dir']

tex_file = argv[1]
